version: "3"
services:
  vksql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vkeducation
      MYSQL_USER: test_qa
      MYSQL_PASSWORD: qa_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
  myapp:
    image: myapp
    command: ["/app/myapp", "--config=/etc/myapp/config.conf"]
    ports:
      - 8080:8080
    volumes:
      - ./myapp/:/etc/myapp/:ro

  vkid_mock:
    build: vkid_mock/.
